name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # або ваша основна гілка

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: |
        docker login -u illuxa2024 -p 112233illya

    - name: Build Docker image
      run: |
        docker build -t yourusername/yourimage:latest .

    - name: Push Docker image to Docker Hub
      run: |
        docker push yourusername/yourimage:latest
