version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf   # виправлена орфографія
    depends_on:
      - php

  php:
    build:
      context: .
    ports:
      - "8888:8888"  # Порти, які будуть відображені на хост-системі

