version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8888:80"  # 8888 на хості буде з'єднано з портом 80 всередині контейнера
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    build:
      context: .  # Будуємо контейнер з поточної директорії
    expose:
      - "80"  # Відкриваємо порт 80 всередині контейнера PHP для внутрішнього зв'язку
