name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # Update to your master branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Login to DockerHub
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/commit-version-website"
          COMMIT_HASH=$(echo $GITHUB_SHA | cut -c1-7)
          IMAGE_TAG="${IMAGE_NAME}:${COMMIT_HASH}"
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG
